name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1.2
      - name: Setup system dependencies
        run: >
          sudo apt-get update && sudo apt-get install --yes
          libcurl4-openssl-dev
      - name: Install R packages
        run: Rscript -e 'install.packages("shiny")'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm install cypress --save-dev
          start: npm run run-app
          wait-on: "http://localhost:5555"
          wait-on-timeout: 500
